---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 package
    apt: name=apache2 update_cache=yes state=latest
    
  - name: Copy html file to apache servers root
    ansible.builtin.copy:
     src: ~/Desktop/index.html
     dest: /var/www/html
    
  - name: apache2 listen on port 8080
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
    notify:
     - restart apache2

  - name: apache2 virtualhost on port 8080
    lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8080>" state=present
    notify:
     - restart apache2

  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
